export const CELO_CHAIN = "CELO_CHAIN";
export const CELO_PUBLIC_CLIENT = "CELO_PUBLIC_CLIENT";
export const CELO_WALLET_CLIENT = "CELO_WALLET_CLIENT";
export const COOP_FACTORY_ABI = "COOP_FACTORY_ABI";
export const COOPERATIVE_VAULT_ABI = "COOPERATIVE_VAULT_ABI";
export const GAS_RELAYER_ABI = "GAS_RELAYER_ABI";
export const COOP_FACTORY_ADDRESS = "COOP_FACTORY_ADDRESS";
export const GAS_RELAYER_ADDRESS = "GAS_RELAYER_ADDRESS";
