/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace CooperativeVault {
  export type ProposalStruct = {
    id: PromiseOrValue<BigNumberish>;
    title: PromiseOrValue<string>;
    description: PromiseOrValue<string>;
    yesVotes: PromiseOrValue<BigNumberish>;
    noVotes: PromiseOrValue<BigNumberish>;
    resolved: PromiseOrValue<boolean>;
    approved: PromiseOrValue<boolean>;
    createdAt: PromiseOrValue<BigNumberish>;
  };

  export type ProposalStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    boolean,
    boolean,
    BigNumber
  ] & {
    id: BigNumber;
    title: string;
    description: string;
    yesVotes: BigNumber;
    noVotes: BigNumber;
    resolved: boolean;
    approved: boolean;
    createdAt: BigNumber;
  };
}

export interface CooperativeVaultInterface extends utils.Interface {
  functions: {
    "admin()": FunctionFragment;
    "contribute(address,uint256)": FunctionFragment;
    "cooperativeName()": FunctionFragment;
    "createProposal(address,string,string)": FunctionFragment;
    "getMemberContribution(address)": FunctionFragment;
    "getProposal(uint256)": FunctionFragment;
    "hasVoted(uint256,address)": FunctionFragment;
    "memberContributions(address)": FunctionFragment;
    "proposalCount()": FunctionFragment;
    "proposals(uint256)": FunctionFragment;
    "relayer()": FunctionFragment;
    "releaseFunds(address,uint256,uint256)": FunctionFragment;
    "targetAmountXAF()": FunctionFragment;
    "totalContributedXAF()": FunctionFragment;
    "vote(address,uint256,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "admin"
      | "contribute"
      | "cooperativeName"
      | "createProposal"
      | "getMemberContribution"
      | "getProposal"
      | "hasVoted"
      | "memberContributions"
      | "proposalCount"
      | "proposals"
      | "relayer"
      | "releaseFunds"
      | "targetAmountXAF"
      | "totalContributedXAF"
      | "vote"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cooperativeName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberContribution",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "memberContributions",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "targetAmountXAF",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalContributedXAF",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cooperativeName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "memberContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetAmountXAF",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalContributedXAF",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;

  events: {
    "ContributionMade(address,uint256,uint256,uint256)": EventFragment;
    "FundsReleased(address,uint256,uint256,uint256)": EventFragment;
    "ProposalCreated(uint256,address,string,uint256)": EventFragment;
    "ProposalResolved(uint256,bool,uint256,uint256)": EventFragment;
    "VoteCast(uint256,address,bool,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContributionMade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundsReleased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalResolved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VoteCast"): EventFragment;
}

export interface ContributionMadeEventObject {
  member: string;
  amountXAF: BigNumber;
  totalXAF: BigNumber;
  timestamp: BigNumber;
}
export type ContributionMadeEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  ContributionMadeEventObject
>;

export type ContributionMadeEventFilter =
  TypedEventFilter<ContributionMadeEvent>;

export interface FundsReleasedEventObject {
  recipient: string;
  amountXAF: BigNumber;
  proposalId: BigNumber;
  timestamp: BigNumber;
}
export type FundsReleasedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  FundsReleasedEventObject
>;

export type FundsReleasedEventFilter = TypedEventFilter<FundsReleasedEvent>;

export interface ProposalCreatedEventObject {
  proposalId: BigNumber;
  creator: string;
  title: string;
  timestamp: BigNumber;
}
export type ProposalCreatedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  ProposalCreatedEventObject
>;

export type ProposalCreatedEventFilter = TypedEventFilter<ProposalCreatedEvent>;

export interface ProposalResolvedEventObject {
  proposalId: BigNumber;
  approved: boolean;
  yesVotes: BigNumber;
  noVotes: BigNumber;
}
export type ProposalResolvedEvent = TypedEvent<
  [BigNumber, boolean, BigNumber, BigNumber],
  ProposalResolvedEventObject
>;

export type ProposalResolvedEventFilter =
  TypedEventFilter<ProposalResolvedEvent>;

export interface VoteCastEventObject {
  proposalId: BigNumber;
  voter: string;
  choice: boolean;
  yesVotes: BigNumber;
  noVotes: BigNumber;
  timestamp: BigNumber;
}
export type VoteCastEvent = TypedEvent<
  [BigNumber, string, boolean, BigNumber, BigNumber, BigNumber],
  VoteCastEventObject
>;

export type VoteCastEventFilter = TypedEventFilter<VoteCastEvent>;

export interface CooperativeVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CooperativeVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    admin(overrides?: CallOverrides): Promise<[string]>;

    contribute(
      member: PromiseOrValue<string>,
      amountXAF: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cooperativeName(overrides?: CallOverrides): Promise<[string]>;

    createProposal(
      creator: PromiseOrValue<string>,
      title: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getMemberContribution(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getProposal(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[CooperativeVault.ProposalStructOutput]>;

    hasVoted(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    memberContributions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    proposalCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    proposals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        BigNumber
      ] & {
        id: BigNumber;
        title: string;
        description: string;
        yesVotes: BigNumber;
        noVotes: BigNumber;
        resolved: boolean;
        approved: boolean;
        createdAt: BigNumber;
      }
    >;

    relayer(overrides?: CallOverrides): Promise<[string]>;

    releaseFunds(
      recipient: PromiseOrValue<string>,
      amountXAF: PromiseOrValue<BigNumberish>,
      proposalId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    targetAmountXAF(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalContributedXAF(overrides?: CallOverrides): Promise<[BigNumber]>;

    vote(
      voter: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BigNumberish>,
      choice: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  admin(overrides?: CallOverrides): Promise<string>;

  contribute(
    member: PromiseOrValue<string>,
    amountXAF: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cooperativeName(overrides?: CallOverrides): Promise<string>;

  createProposal(
    creator: PromiseOrValue<string>,
    title: PromiseOrValue<string>,
    description: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getMemberContribution(
    member: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getProposal(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<CooperativeVault.ProposalStructOutput>;

  hasVoted(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  memberContributions(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

  proposals(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      BigNumber,
      BigNumber,
      boolean,
      boolean,
      BigNumber
    ] & {
      id: BigNumber;
      title: string;
      description: string;
      yesVotes: BigNumber;
      noVotes: BigNumber;
      resolved: boolean;
      approved: boolean;
      createdAt: BigNumber;
    }
  >;

  relayer(overrides?: CallOverrides): Promise<string>;

  releaseFunds(
    recipient: PromiseOrValue<string>,
    amountXAF: PromiseOrValue<BigNumberish>,
    proposalId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  targetAmountXAF(overrides?: CallOverrides): Promise<BigNumber>;

  totalContributedXAF(overrides?: CallOverrides): Promise<BigNumber>;

  vote(
    voter: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BigNumberish>,
    choice: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    admin(overrides?: CallOverrides): Promise<string>;

    contribute(
      member: PromiseOrValue<string>,
      amountXAF: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cooperativeName(overrides?: CallOverrides): Promise<string>;

    createProposal(
      creator: PromiseOrValue<string>,
      title: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getMemberContribution(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposal(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<CooperativeVault.ProposalStructOutput>;

    hasVoted(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    memberContributions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

    proposals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        BigNumber
      ] & {
        id: BigNumber;
        title: string;
        description: string;
        yesVotes: BigNumber;
        noVotes: BigNumber;
        resolved: boolean;
        approved: boolean;
        createdAt: BigNumber;
      }
    >;

    relayer(overrides?: CallOverrides): Promise<string>;

    releaseFunds(
      recipient: PromiseOrValue<string>,
      amountXAF: PromiseOrValue<BigNumberish>,
      proposalId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    targetAmountXAF(overrides?: CallOverrides): Promise<BigNumber>;

    totalContributedXAF(overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      voter: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BigNumberish>,
      choice: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ContributionMade(address,uint256,uint256,uint256)"(
      member?: PromiseOrValue<string> | null,
      amountXAF?: null,
      totalXAF?: null,
      timestamp?: null
    ): ContributionMadeEventFilter;
    ContributionMade(
      member?: PromiseOrValue<string> | null,
      amountXAF?: null,
      totalXAF?: null,
      timestamp?: null
    ): ContributionMadeEventFilter;

    "FundsReleased(address,uint256,uint256,uint256)"(
      recipient?: PromiseOrValue<string> | null,
      amountXAF?: null,
      proposalId?: PromiseOrValue<BigNumberish> | null,
      timestamp?: null
    ): FundsReleasedEventFilter;
    FundsReleased(
      recipient?: PromiseOrValue<string> | null,
      amountXAF?: null,
      proposalId?: PromiseOrValue<BigNumberish> | null,
      timestamp?: null
    ): FundsReleasedEventFilter;

    "ProposalCreated(uint256,address,string,uint256)"(
      proposalId?: PromiseOrValue<BigNumberish> | null,
      creator?: PromiseOrValue<string> | null,
      title?: null,
      timestamp?: null
    ): ProposalCreatedEventFilter;
    ProposalCreated(
      proposalId?: PromiseOrValue<BigNumberish> | null,
      creator?: PromiseOrValue<string> | null,
      title?: null,
      timestamp?: null
    ): ProposalCreatedEventFilter;

    "ProposalResolved(uint256,bool,uint256,uint256)"(
      proposalId?: PromiseOrValue<BigNumberish> | null,
      approved?: null,
      yesVotes?: null,
      noVotes?: null
    ): ProposalResolvedEventFilter;
    ProposalResolved(
      proposalId?: PromiseOrValue<BigNumberish> | null,
      approved?: null,
      yesVotes?: null,
      noVotes?: null
    ): ProposalResolvedEventFilter;

    "VoteCast(uint256,address,bool,uint256,uint256,uint256)"(
      proposalId?: PromiseOrValue<BigNumberish> | null,
      voter?: PromiseOrValue<string> | null,
      choice?: null,
      yesVotes?: null,
      noVotes?: null,
      timestamp?: null
    ): VoteCastEventFilter;
    VoteCast(
      proposalId?: PromiseOrValue<BigNumberish> | null,
      voter?: PromiseOrValue<string> | null,
      choice?: null,
      yesVotes?: null,
      noVotes?: null,
      timestamp?: null
    ): VoteCastEventFilter;
  };

  estimateGas: {
    admin(overrides?: CallOverrides): Promise<BigNumber>;

    contribute(
      member: PromiseOrValue<string>,
      amountXAF: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cooperativeName(overrides?: CallOverrides): Promise<BigNumber>;

    createProposal(
      creator: PromiseOrValue<string>,
      title: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getMemberContribution(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposal(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasVoted(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    memberContributions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

    proposals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    relayer(overrides?: CallOverrides): Promise<BigNumber>;

    releaseFunds(
      recipient: PromiseOrValue<string>,
      amountXAF: PromiseOrValue<BigNumberish>,
      proposalId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    targetAmountXAF(overrides?: CallOverrides): Promise<BigNumber>;

    totalContributedXAF(overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      voter: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BigNumberish>,
      choice: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contribute(
      member: PromiseOrValue<string>,
      amountXAF: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cooperativeName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createProposal(
      creator: PromiseOrValue<string>,
      title: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getMemberContribution(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposal(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasVoted(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    memberContributions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposalCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposals(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    relayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    releaseFunds(
      recipient: PromiseOrValue<string>,
      amountXAF: PromiseOrValue<BigNumberish>,
      proposalId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    targetAmountXAF(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalContributedXAF(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vote(
      voter: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BigNumberish>,
      choice: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
